In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("/data1/project/eunyi/networkpropagation/meeting1/10090_protein_df.csv")
df

,protein1,protein2,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score,symbol1,symbol2
0,ENSMUSP00000000001,ENSMUSP00000027991,0.0,0.0,0.0,56.0,594.0,500.0,492.0,889.0,Gnai3,Rgs4
1,ENSMUSP00000000001,ENSMUSP00000137332,0.0,0.0,0.0,0.0,0.0,0.0,163.0,163.0,Gnai3,Cmtm4
2,ENSMUSP00000000001,ENSMUSP00000041756,0.0,0.0,0.0,110.0,117.0,0.0,65.0,201.0,Gnai3,Arl5a
3,ENSMUSP00000000001,ENSMUSP00000075170,0.0,0.0,0.0,0.0,604.0,900.0,301.0,969.0,Gnai3,Drd2
4,ENSMUSP00000000001,ENSMUSP00000110978,0.0,0.0,0.0,48.0,228.0,0.0,84.0,267.0,Gnai3,Grm8
...,...,...,...,...,...,...,...,...,...,...,...,...
678454,ENSMUSP00000007757,ENSMUSP00000065983,0.0,0.0,0.0,78.0,116.0,0.0,120.0,219.0,Tgfbr1,Mapk1
678455,ENSMUSP00000007757,ENSMUSP00000061935,0.0,0.0,0.0,0.0,0.0,0.0,292.0,292.0,Tgfbr1,Epcam
678456,ENSMUSP00000007757,ENSMUSP00000053027,0.0,0.0,0.0,65.0,0.0,0.0,162.0,182.0,Tgfbr1,Fut4
678457,ENSMUSP00000007757,ENSMUSP00000107512,0.0,0.0,0.0,47.0,95.0,0.0,139.0,192.0,Tgfbr1,Nfkb2
678458,ENSMUSP00000007757,ENSMUSP00000044554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# combined_score > 800인 것만 filtering
df = df.query("combined_score > 800")
df

,protein1,protein2,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score,symbol1,symbol2
0,ENSMUSP00000000001,ENSMUSP00000027991,0.0,0.0,0.0,56.0,594.0,500.0,492.0,889.0,Gnai3,Rgs4
3,ENSMUSP00000000001,ENSMUSP00000075170,0.0,0.0,0.0,0.0,604.0,900.0,301.0,969.0,Gnai3,Drd2
7,ENSMUSP00000000001,ENSMUSP00000121127,0.0,0.0,0.0,151.0,639.0,650.0,310.0,916.0,Gnai3,Gnb4
8,ENSMUSP00000000001,ENSMUSP00000081569,0.0,0.0,0.0,90.0,271.0,900.0,425.0,956.0,Gnai3,Rgs3
39,ENSMUSP00000000001,ENSMUSP00000074259,0.0,0.0,47.0,0.0,0.0,900.0,50.0,901.0,Gnai3,Gnai1
...,...,...,...,...,...,...,...,...,...,...,...,...
678380,ENSMUSP00000007757,ENSMUSP00000031224,0.0,0.0,0.0,0.0,98.0,0.0,936.0,939.0,Tgfbr1,Tgfbr3
678385,ENSMUSP00000007757,ENSMUSP00000026408,0.0,0.0,0.0,0.0,753.0,900.0,977.0,999.0,Tgfbr1,Gdf11
678398,ENSMUSP00000007757,ENSMUSP00000025393,0.0,0.0,0.0,64.0,168.0,900.0,932.0,994.0,Tgfbr1,Smad4
678403,ENSMUSP00000007757,ENSMUSP00000023050,0.0,0.0,0.0,0.0,101.0,0.0,824.0,834.0,Tgfbr1,Tab1
678405,ENSMUSP00000007757,ENSMUSP00000062333,0.0,0.0,0.0,194.0,945.0,900.0,986.0,999.0,Tgfbr1,Tgfbr2

In [12]:
# 'symbol1' 열, 'symbol2' 열에서 'No symbol found'를 포함하지 않는 행만 선택
df = df[(df['symbol2'] != 'No symbol found') & (df['symbol1'] != 'No symbol found')]
df

,protein1,protein2,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score,symbol1,symbol2
0,ENSMUSP00000000001,ENSMUSP00000027991,0.0,0.0,0.0,56.0,594.0,500.0,492.0,889.0,Gnai3,Rgs4
3,ENSMUSP00000000001,ENSMUSP00000075170,0.0,0.0,0.0,0.0,604.0,900.0,301.0,969.0,Gnai3,Drd2
7,ENSMUSP00000000001,ENSMUSP00000121127,0.0,0.0,0.0,151.0,639.0,650.0,310.0,916.0,Gnai3,Gnb4
8,ENSMUSP00000000001,ENSMUSP00000081569,0.0,0.0,0.0,90.0,271.0,900.0,425.0,956.0,Gnai3,Rgs3
39,ENSMUSP00000000001,ENSMUSP00000074259,0.0,0.0,47.0,0.0,0.0,900.0,50.0,901.0,Gnai3,Gnai1
...,...,...,...,...,...,...,...,...,...,...,...,...
678380,ENSMUSP00000007757,ENSMUSP00000031224,0.0,0.0,0.0,0.0,98.0,0.0,936.0,939.0,Tgfbr1,Tgfbr3
678385,ENSMUSP00000007757,ENSMUSP00000026408,0.0,0.0,0.0,0.0,753.0,900.0,977.0,999.0,Tgfbr1,Gdf11
678398,ENSMUSP00000007757,ENSMUSP00000025393,0.0,0.0,0.0,64.0,168.0,900.0,932.0,994.0,Tgfbr1,Smad4
678403,ENSMUSP00000007757,ENSMUSP00000023050,0.0,0.0,0.0,0.0,101.0,0.0,824.0,834.0,Tgfbr1,Tab1
678405,ENSMUSP00000007757,ENSMUSP00000062333,0.0,0.0,0.0,194.0,945.0,900.0,986.0,999.0,Tgfbr1,Tgfbr2

In [13]:
df.to_csv("/data1/project/eunyi/tbi/drug_gene/protein_filter_800.csv", index=False)
protein_filter_800 = pd.read_csv("/data1/project/eunyi/tbi/drug_gene/protein_filter_800.csv")
protein_filter_800

,protein1,protein2,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score,symbol1,symbol2
0,ENSMUSP00000000001,ENSMUSP00000027991,0.0,0.0,0.0,56.0,594.0,500.0,492.0,889.0,Gnai3,Rgs4
1,ENSMUSP00000000001,ENSMUSP00000075170,0.0,0.0,0.0,0.0,604.0,900.0,301.0,969.0,Gnai3,Drd2
2,ENSMUSP00000000001,ENSMUSP00000121127,0.0,0.0,0.0,151.0,639.0,650.0,310.0,916.0,Gnai3,Gnb4
3,ENSMUSP00000000001,ENSMUSP00000081569,0.0,0.0,0.0,90.0,271.0,900.0,425.0,956.0,Gnai3,Rgs3
4,ENSMUSP00000000001,ENSMUSP00000074259,0.0,0.0,47.0,0.0,0.0,900.0,50.0,901.0,Gnai3,Gnai1
...,...,...,...,...,...,...,...,...,...,...,...,...
14738,ENSMUSP00000007757,ENSMUSP00000031224,0.0,0.0,0.0,0.0,98.0,0.0,936.0,939.0,Tgfbr1,Tgfbr3
14739,ENSMUSP00000007757,ENSMUSP00000026408,0.0,0.0,0.0,0.0,753.0,900.0,977.0,999.0,Tgfbr1,Gdf11
14740,ENSMUSP00000007757,ENSMUSP00000025393,0.0,0.0,0.0,64.0,168.0,900.0,932.0,994.0,Tgfbr1,Smad4
14741,ENSMUSP00000007757,ENSMUSP00000023050,0.0,0.0,0.0,0.0,101.0,0.0,824.0,834.0,Tgfbr1,Tab1
14742,ENSMUSP00000007757,ENSMUSP00000062333,0.0,0.0,0.0,194.0,945.0,900.0,986.0,999.0,Tgfbr1,Tgfbr2

In [14]:
input_graph_800 = protein_filter_800[['symbol1', 'symbol2', 'combined_score']].to_csv(index=False, header=False, sep='\t')
with open('/data1/project/eunyi/tbi/drug_gene/input_graph_800.txt', 'w') as f:
    f.write(input_graph_800)

In [15]:
# 파일 경로 설정
file_path = '/data1/project/eunyi/tbi/drug_gene/input_graph_800.txt'

# 데이터 불러오기
input_graph_800 = pd.read_csv(file_path, sep='\t', header=None, names=['symbol1', 'symbol2', 'combined_score'])

# symbol1의 고유 개수
unique_symbol1 = input_graph_800['symbol1'].nunique()

# protein2의 고유 개수
unique_symbol2 = input_graph_800['symbol2'].nunique()

# 데이터의 shape
data_shape = input_graph_800.shape

print("symbol1의 고유 개수:", unique_symbol1)
print("symbol2의 고유 개수:", unique_symbol2)
print("input_graph_800의 shape:", data_shape)

symbol1의 고유 개수: 624
symbol2의 고유 개수: 5793
input_graph_800의 shape: (14743, 3)

In [16]:
unique_symbols = pd.concat([input_graph_800['symbol1'], input_graph_800['symbol2']]).nunique()

print("고유한 protein의 개수:", unique_symbols)

고유한 protein의 개수: 6050

In [17]:
max_combined_score = input_graph_800['combined_score'].max()
max_combined_score

999.0

In [23]:
output_sub_up = pd.read_csv('0.adjusted_subacute_up.txt', sep='\t', header=None, names=['gene', 'np_score'])
# Apply the formatting only to the 'score' column
output_sub_up['np_score'] = output_sub_up['np_score'].apply(lambda x: f'{x:.6f}')
# Display the updated DataFrame
output_sub_up = output_sub_up.sort_values(by='np_score', ascending=False)
output_sub_up

       gene  np_score
1735  Ephx1  0.010654
2212   Gpx1  0.010581
3318  Msmo1  0.010475
2306   Gypa  0.010457
219   Alas2  0.010457
...     ...       ...
2142   Gmnn  0.000000
2141   Gmfg  0.000000
2140   Gmfb  0.000000
2139  Gm973  0.000000
6049   Zzz3  0.000000

[6050 rows x 2 columns]

In [27]:
subacute_df = pd.read_csv("/data1/project/eunyi/tbi/0.bowht_subacute_deseq2_gene.csv", index_col=0)
subacute_df

,gene,TBI Subacute vs SControl Log2 fold change,Subacute pval,Subacute padj
0,Gnai3,-0.004249,0.981357,0.998485
1,Pbsn,NaN,NaN,NaN
2,Cdc45,0.048852,0.908633,0.991531
3,H19,-6.060255,0.000113,0.010768
4,Scml2,-0.645345,0.673700,NaN
...,...,...,...,...
37654,Mir3101,NaN,NaN,NaN
37657,Mir3072,-1.636198,0.738546,NaN
37660,Mir125b-1,2.684989,0.568425,NaN
37661,Snora26,NaN,NaN,NaN
37664,Mir3063,NaN,NaN,NaN

In [30]:
subacute_df['Subacute-log10(p_value)'] = -np.log10(subacute_df['Subacute pval'])
subacute_df['Subacute-log10(padj)'] = -np.log10(subacute_df['Subacute padj'])

In [31]:
subacute_df.dropna(inplace=True)

In [32]:
subacute_df.columns

Index(['gene', 'TBI Subacute vs SControl Log2 fold change', 'Subacute pval',
       'Subacute padj', 'Subacute-log10(p_value)', 'Subacute-log10(padj)'],
      dtype='object')

In [33]:
subacute_df.to_csv("/data1/project/eunyi/tbi/drug_gene/bowht_subacute_deseq2_gene.csv")

In [35]:
subacute_df = pd.read_csv("/data1/project/eunyi/tbi/drug_gene/bowht_subacute_deseq2_gene.csv", index_col=0)
subacute_df

,gene,TBI Subacute vs SControl Log2 fold change,Subacute pval,Subacute padj,Subacute-log10(p_value),Subacute-log10(padj)
0,Gnai3,-0.004249,0.981357,0.998485,0.008173,0.000659
2,Cdc45,0.048852,0.908633,0.991531,0.041611,0.003694
3,H19,-6.060255,0.000113,0.010768,3.948192,1.967884
6,Narf,-0.041851,0.849998,0.986401,0.070582,0.005947
7,Cav2,0.270668,0.196677,0.770430,0.706246,0.113267
...,...,...,...,...,...,...
37403,Mir3097,0.581393,0.607398,0.949260,0.216527,0.022615
37446,Mir28b,-0.180842,0.824064,0.981962,0.084039,0.007905
37453,Gm23369,0.196796,0.845287,0.985728,0.072996,0.006243
37583,Gm26236,-0.040380,0.897184,0.989398,0.047118,0.004629
37642,Mir1954,-0.578058,0.507684,0.920720,0.294407,0.035872

In [36]:
subacute_df_up = subacute_df[(subacute_df['Subacute padj'] < 0.22)  & (subacute_df['TBI Subacute vs SControl Log2 fold change'] > 0.4)]
subacute_df_up

,gene,TBI Subacute vs SControl Log2 fold change,Subacute pval,Subacute padj,Subacute-log10(p_value),Subacute-log10(padj)
59,Alox12,0.658976,0.007463,0.192069,2.127077,0.716542
141,Car4,0.713462,0.000225,0.017646,3.647480,1.753358
153,Dbh,5.894632,0.000005,0.000845,5.328697,3.073064
178,Icam2,0.601700,0.003127,0.109627,2.504926,0.960082
258,Cyp51,0.836614,0.000593,0.034730,3.227031,1.459295
...,...,...,...,...,...,...
28992,Gm16418,0.866763,0.002315,0.089485,2.635381,1.048252
29148,Gm12040,1.328665,0.009237,0.215124,2.034448,0.667310
34139,Gm15946,1.090595,0.000386,0.025665,3.412903,1.590663
35868,Gm6665,0.768234,0.001819,0.075044,2.740050,1.124681
37036,Snora24,1.111856,0.000123,0.011481,3.909467,1.940030

In [40]:
subacute_df_down = subacute_df[(subacute_df['Subacute padj'] < 0.0002)  & (subacute_df['TBI Subacute vs SControl Log2 fold change'] < -1.3)]
subacute_df_down

,gene,TBI Subacute vs SControl Log2 fold change,Subacute pval,Subacute padj,Subacute-log10(p_value),Subacute-log10(padj)
176,S100a6,-2.243927,3.432069e-11,2.151633e-08,10.464444,7.667232
267,Col1a1,-2.174308,3.090623e-09,1.562559e-06,8.509954,5.806164
679,Cacna1e,-1.496181,2.177658e-11,1.706521e-08,10.662010,7.767888
805,Cd44,-1.877687,2.798390e-07,7.433757e-05,6.553092,4.128792
965,Fblim1,-1.917497,6.333392e-07,1.459754e-04,6.198364,3.835720
1002,Adamts4,-2.189989,2.208396e-13,2.995081e-10,12.655923,9.523591
1408,Kif11,-2.531327,1.085817e-07,3.545417e-05,6.964244,4.450333
1443,Aldh1a2,-1.770727,7.658159e-09,3.429324e-06,8.115876,5.464792
2467,Hmmr,-4.921674,1.581153e-11,1.304285e-08,10.801026,7.884628
2510,Upp1,-2.537047,1.903680e-07,5.647493e-05,6.720406,4.248144
2568,Prr11,-2.718935,5.505359e-07,1.327469e-04,6.259214,3.876976
2684,Itgb3,-1.502784,9.858822e-08,3.287603e-05,7.006175,4.483121
2833,Top2a,-3.053891,1.045880e-11,9.642395e-09,10.980518,8.015815
3214,Vcan,-2.422560,3.626457e-14,6.315274e-11,13.440517,10.199608
3459,Pbk,-4.455513,1.909763e-07,5.647493e-05,6.719021,4.248144
4102,Slc38a1,-2.440967,6.117895e-07,1.431131e-04,6.213398,3.844321
4312,Cyp1b1,-1.767723,3.099014e-11,2.023785e-08,10.508777,7.693836
5352,Col3a1,-1.933729,2.361451e-11,1.762430e-08,10.626821,7.753888
5432,Igfbp5,-2.795812,3.975581e-18,1.557732e-14,17.400599,13.807507
5656,Selp,-4.197029,1.858848e-12,1.820857e-09,11.730756,8.739724
5658,Sele,-2.390917,2.484276e-13,2.995081e-10,12.604800,9.523591
5672,Cenpf,-3.134380,1.194842e-13,1.872675e-10,12.922690,9.727538
5820,Col5a1,-2.994237,3.625274e-10,2.104404e-07,9.440659,6.676871
6166,Tpx2,-2.640948,7.690415e-07,1.697632e-04,6.114050,3.770156
6306,Ccna2,-2.524315,6.694162e-08,2.331502e-05,7.174304,4.632364
6669,Tnfsf8,-3.324487,1.403677e-12,1.466656e-09,11.852733,8.833672
6670,Tnc,-5.401363,1.451079e-20,7.580923e-17,19.838309,16.120278
7041,Tnfrsf9,-3.311448,3.285838e-09,1.609342e-06,8.483354,5.793352
7132,Pcdh7,-3.782272,1.196379e-11,1.041713e-08,10.922131,7.982252
7480,Col1a2,-1.677327,1.282378e-08,5.432082e-06,7.891984,5.265034
8168,Mki67,-2.719202,8.820903e-17,2.765000e-13,16.054487,12.558305
8204,Elf4,-1.700723,3.640074e-08,1.396988e-05,7.438890,4.854807
8643,Cdh13,-2.341019,3.457967e-14,6.315274e-11,13.461179,10.199608
8744,Adamts8,-1.962391,2.150858e-07,6.129164e-05,6.667388,4.212599
8754,Thy1,-3.392489,3.472529e-09,1.649241e-06,8.459354,5.782716
9036,Ptgs2,-1.723192,2.400989e-09,1.254357e-06,8.619610,5.901579
9074,Slco2a1,-2.605891,4.993586e-15,1.118064e-11,14.301587,10.951533
9075,Rab6b,-3.872876,1.144612e-26,8.969751e-23,25.941342,22.047220
9542,Aspm,-2.235577,3.111565e-07,8.127926e-05,6.507021,4.090020
10232,Cd276,-1.857238,3.337483e-08,1.341240e-05,7.476581,4.872493
10502,Anln,-2.869150,1.677181e-08,6.917489e-06,7.775420,5.160052
10621,Inhbb,-2.987652,7.132933e-08,2.430314e-05,7.146732,4.614338
10635,Lrg1,-5.494985,2.489882e-37,3.902392e-33,36.603821,32.408669
11625,Atp8b1,-2.497597,3.355326e-13,3.756288e-10,12.474265,9.425241
11762,Fgl2,-1.789529,2.464928e-07,6.777687e-05,6.608196,4.168919
12038,Ildr2,-1.780238,1.612498e-15,4.212113e-12,14.792501,11.375500
13502,Cenpe,-2.901552,4.026422e-09,1.856062e-06,8.395081,5.731407
13744,Cd109,-3.331644,1.174521e-09,6.347681e-07,8.930139,6.197385
14454,Myof,-1.375346,3.654471e-08,1.396988e-05,7.437176,4.854807
14937,Ch25h,-1.975787,8.824424e-09,3.841811e-06,8.054314,5.415464
15031,Plekho2,-1.438533,4.497095e-08,1.601886e-05,7.347068,4.795369
15252,Cd14,-1.744474,4.540487e-07,1.147791e-04,6.342898,3.940137
15992,Adam12,-2.303249,1.203347e-07,3.772012e-05,6.919609,4.423427
16105,Pdlim1,-1.954224,2.940807e-11,2.023785e-08,10.531534,7.693836
20051,Nnat,-1.395626,7.957296e-07,1.732149e-04,6.099234,3.761415
31966,2610035D17Rik,-2.802027,2.562359e-07,6.924113e-05,6.591360,4.159636

In [41]:
up_deg = subacute_df[(subacute_df['Subacute padj'] < 0.22) & (subacute_df['TBI Subacute vs SControl Log2 fold change'] > 0.4)]
down_deg = subacute_df[(subacute_df['Subacute padj'] < 0.0002) & (subacute_df['TBI Subacute vs SControl Log2 fold change'] < -1.3)]
output_sub_up = pd.read_csv('0.adjusted_subacute_up.txt', sep='\t', header=None, names=['gene', 'score'])
output_sub_down = pd.read_csv('0.adjusted_subacute_down.txt', sep='\t', header=None, names=['gene', 'score'])
merged_up = up_deg.merge(output_sub_up, left_on='gene', right_on='gene')
merged_down = down_deg.merge(output_sub_down, left_on='gene', right_on='gene')

print(merged_up)
print(merged_down)

      gene  TBI Subacute vs SControl Log2 fold change  Subacute pval  \
0   Alox12                                   0.658976       0.007463
1      Dbh                                   5.894632       0.000005
2    Icam2                                   0.601700       0.003127
3    Cyp51                                   0.836614       0.000593
4   Nherf2                                   0.485697       0.005427
..     ...                                        ...            ...
58  Lsm14a                                   0.630415       0.004640
59  Hba-a2                                   1.529602       0.000096
60    Jund                                   0.747157       0.002539
61   Cebpd                                   0.752518       0.003194
62  Tuba1a                                   0.683995       0.001064

    Subacute padj  Subacute-log10(p_value)  Subacute-log10(padj)     score
0        0.192069                 2.127077              0.716542  0.010022
1        0.000845                 5.328697              3.073064  0.010024
2        0.109627                 2.504926              0.960082  0.010096
3        0.034730                 3.227031              1.459295  0.010042
4        0.154390                 2.265440              0.811381  0.010285
..            ...                      ...                   ...       ...
58       0.140372                 2.333490              0.852720  0.010000
59       0.009741                 4.019524              2.011378  0.010001
60       0.095667                 2.595296              1.019237  0.010000
61       0.110657                 2.495663              0.956020  0.010000
62       0.053454                 2.973018              1.272020  0.010000

[63 rows x 7 columns]
       gene  TBI Subacute vs SControl Log2 fold change  Subacute pval  \
0    S100a6                                  -2.243927   3.432069e-11
1    Col1a1                                  -2.174308   3.090623e-09
2      Cd44                                  -1.877687   2.798390e-07
3    Fblim1                                  -1.917497   6.333392e-07
4     Kif11                                  -2.531327   1.085817e-07
5   Aldh1a2                                  -1.770727   7.658159e-09
6      Hmmr                                  -4.921674   1.581153e-11
7      Upp1                                  -2.537047   1.903680e-07
8     Itgb3                                  -1.502784   9.858822e-08
9     Top2a                                  -3.053891   1.045880e-11
10     Vcan                                  -2.422560   3.626457e-14
11      Pbk                                  -4.455513   1.909763e-07
12   Cyp1b1                                  -1.767723   3.099014e-11
13   Col3a1                                  -1.933729   2.361451e-11
14     Selp                                  -4.197029   1.858848e-12
15     Sele                                  -2.390917   2.484276e-13
16    Cenpf                                  -3.134380   1.194842e-13
17   Col5a1                                  -2.994237   3.625274e-10
18    Ccna2                                  -2.524315   6.694162e-08
19   Col1a2                                  -1.677327   1.282378e-08
20    Mki67                                  -2.719202   8.820903e-17
21    Cdh13                                  -2.341019   3.457967e-14
22     Thy1                                  -3.392489   3.472529e-09
23    Ptgs2                                  -1.723192   2.400989e-09
24     Aspm                                  -2.235577   3.111565e-07
25    Cd276                                  -1.857238   3.337483e-08
26     Anln                                  -2.869150   1.677181e-08
27    Inhbb                                  -2.987652   7.132933e-08
28    Cenpe                                  -2.901552   4.026422e-09
29    Ch25h                                  -1.975787   8.824424e-09
30     Cd14                                  -1.744474   4.540487e-07

    Subacute padj  Subacute-log10(p_value)  Subacute-log10(padj)     score
0    2.151633e-08                10.464444              7.667232  0.010000
1    1.562559e-06                 8.509954              5.806164  0.010127
2    7.433757e-05                 6.553092              4.128792  0.010248
3    1.459754e-04                 6.198364              3.835720  0.010000
4    3.545417e-05                 6.964244              4.450333  0.010000
5    3.429324e-06                 8.115876              5.464792  0.010000
6    1.304285e-08                10.801026              7.884628  0.010075
7    5.647493e-05                 6.720406              4.248144  0.010000
8    3.287603e-05                 7.006175              4.483121  0.010303
9    9.642395e-09                10.980518              8.015815  0.010000
10   6.315274e-11                13.440517             10.199608  0.010075
11   5.647493e-05                 6.719021              4.248144  0.010000
12   2.023785e-08                10.508777              7.693836  0.010000
13   1.762430e-08                10.626821              7.753888  0.010250
14   1.820857e-09                11.730756              8.739724  0.010075
15   2.995081e-10                12.604800              9.523591  0.010075
16   1.872675e-10                12.922690              9.727538  0.010000
17   2.104404e-07                 9.440659              6.676871  0.010250
18   2.331502e-05                 7.174304              4.632364  0.010000
19   5.432082e-06                 7.891984              5.265034  0.010325
20   2.765000e-13                16.054487             12.558305  0.010001
21   6.315274e-11                13.461179             10.199608  0.010000
22   1.649241e-06                 8.459354              5.782716  0.010076
23   1.254357e-06                 8.619610              5.901579  0.010001
24   8.127926e-05                 6.507021              4.090020  0.010000
25   1.341240e-05                 7.476581              4.872493  0.010000
26   6.917489e-06                 7.775420              5.160052  0.010000
27   2.430314e-05                 7.146732              4.614338  0.010003
28   1.856062e-06                 8.395081              5.731407  0.010000
29   3.841811e-06                 8.054314              5.415464  0.010000
30   1.147791e-04                 6.342898              3.940137  0.010000

In [39]:
merged_up.sort_values(by='score', ascending=False)

,gene,TBI Subacute vs SControl Log2 fold change,Subacute pval,Subacute padj,Subacute-log10(p_value),Subacute-log10(padj),score
42,Ephx1,0.879995,0.000102,0.009969,3.993035,2.001339,0.010654
56,Gpx1,0.589199,0.003294,0.111864,2.482258,0.951308,0.010581
34,Msmo1,0.772088,0.007810,0.197435,2.107337,0.704576,0.010475
50,Gypa,0.914030,0.008608,0.208192,2.065114,0.681537,0.010457
26,Alas2,0.923325,0.000041,0.004997,4.382470,2.301262,0.010457
...,...,...,...,...,...,...,...
49,Vamp8,0.548651,0.007260,0.188736,2.139050,0.724146,0.010000
47,Uqcrq,0.763629,0.002820,0.102453,2.549803,0.989476,0.010000
55,Ptp4a3,0.561673,0.008452,0.207612,2.073056,0.682748,0.010000
57,ND6,0.730957,0.000443,0.028109,3.353611,1.551156,0.010000
62,Tuba1a,0.683995,0.001064,0.053454,2.973018,1.272020,0.010000

In [43]:
subacute_up_gene_np = merged_up[["gene", "score"]]
subacute_up_gene_np = subacute_up_gene_np.rename(columns={"score": "np_score"})
subacute_up_gene_np.to_csv("/data1/project/eunyi/tbi/drug_gene/1.subacute_up_gene_np.csv", index=False)
subacute_up_gene_np.sort_values(by='np_score', ascending=False)

      gene  np_score
42   Ephx1  0.010654
56    Gpx1  0.010581
34   Msmo1  0.010475
50    Gypa  0.010457
26   Alas2  0.010457
..     ...       ...
49   Vamp8  0.010000
47   Uqcrq  0.010000
55  Ptp4a3  0.010000
57     ND6  0.010000
62  Tuba1a  0.010000

[63 rows x 2 columns]